### ISSUE TITLE
Undocumented change for keepAliveViaLanInterfaceEnabled

### ISSUE THREAD

**Issue by EnchiladaCloud** [terraform-aviatrix-modules/terraform-aviatrix-mc-firenet#17]
In the latest release 1.5.1 there is an undocumented change for the "keepAliveViaLanInterfaceEnabled" setting. This change will cause an change from false to true for the deault value. The variable is commented out and can't be overwritten per default via module call. If you try to apply the new default behaivor, you get the following error message:

Error: could not enable keep alive via lan interface while updating firenet: rest API edit_firenet(lan_ping=true) Post failed: [AVXERR-FIRENET-0037] Keep Alive via Firewall Lan Interface is not supported for FireNet with Load Balancer.

**Comment by Dennizz** [comment]
Looks like a change in preparation for 7.2 slipped in. My bad. Will retract 1.5.1 and release 1.5.2 without that change embedded asap.

Thanks for raising this.

**Comment by Dennizz** [comment]
1.5.2 released. Closing this.
