### ISSUE TITLE
Add support of "key_name" in AWS for customized key pair

### ISSUE THREAD

**Issue by jwang-avx** [terraform-aviatrix-modules/terraform-aviatrix-mc-firenet#3]
The "key_name" is currently not available in the module. Please help add when possible. 

https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_firewall_instance#key_name

**Comment by Dennizz** [comment]
Implemented:
https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-firenet/commit/7c26b87b1a8631c65909ac7c1e63d08356f9fc91

Will be part of next release.

**Comment by jwang-avx** [comment]
Awesome! Cheers!
