### ISSUE TITLE
variable "password" not beeing nullable

### ISSUE THREAD

**Issue by mbockmannsva** [terraform-aviatrix-modules/terraform-aviatrix-mc-firenet#5]
Currently the password for the firewall instances isn't beeing nullable.

If you are using ssh_public_key (currently not part of the module) at azure for the firewall login, the password has to be nulled.

If possible add ssh_public_key to the module and make it possible to "true" to null variable password.

**Comment by Dennizz** [comment]
Changes implemented in main branch (Thanks @astipkovits). Please use and test with source:
`source = "git::https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-firenet"` for the moment. I will be releasing a new version after my holiday.
