### ISSUE TITLE
System generated Firewall instance name is not accepted by GCP

### ISSUE THREAD

**Issue by snukala417** [terraform-aviatrix-modules/terraform-aviatrix-mc-firenet#9]
Controller Version:  7.0.1034

While creating Firewall instance, name is generated by terraform module.  On GCP, system generated firewall instance name (firewall_instance_1) is rejected 

Terraform Code:

module "transit_ha_gcp" {
  source  = "terraform-aviatrix-modules/mc-transit/aviatrix"
  version = "2.1.3"

  cloud                  = "gcp"
  name                   = "gcp-transit-firenet"
  region                 = var.region
  cidr                   = var.cidr
  account                = var.account_name
  instance_size          = var.transit_size
  insane_mode            = true
  enable_transit_firenet = true
  lan_cidr               = var.lan_cidr
}

module "mc_firenet_ha_gcp" {
  source  = "terraform-aviatrix-modules/mc-firenet/aviatrix"
  version = "1.1.1"

  transit_module = module.transit_ha_gcp
  firewall_image = "Palo Alto Networks VM-Series Next-Generation Firewall BYOL"
  #firewall_image = "Palo Alto Networks VM-Series Next-Generation Firewall BUNDLE2"
  custom_fw_names = ["gcp-fw-instance-1", "gcp-fw-instance-hagw-1"]
  firewall_image_version = "9.0.9"
  egress_enabled = true
  egress_cidr    = var.egress_cidr
  mgmt_cidr      = var.mgmt_cidr
  instance_size  = var.firewall_size
  bootstrap_bucket_name_1 = "pan_bootstrap"
  fw_amount               = 2
}

ERROR:

module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_1[0]: Creating...
module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_2[0]: Creating...
module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_2[0]: Still creating... [10s elapsed]
module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_1[0]: Still creating... [10s elapsed]
╷
│ Error: failed to create a new firewall instance: rest API add_firewall_instance POST failed: command dmz_action failed due to exception errors Project was not passed and could not be dete
rmined from the environment.<p></p> An email notification with exception reason and trace log has been sent to [exceptions@aviatrix.com](mailto:exceptions@aviatrix.com) for troubleshooting. Please feel free to contact Aviatrix support. We apologize for this inconvenience and we thank you for your support.
│
│   with module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_1[0],
│   on .terraform/modules/gcp_transit.mc_firenet_ha_gcp/main.tf line 35, in resource "aviatrix_firewall_instance" "firewall_instance_1":
│   35: resource "aviatrix_firewall_instance" "firewall_instance_1" {
│
╵
╷
│ Error: failed to create a new firewall instance: rest API add_firewall_instance POST failed: command dmz_action failed due to exception errors Project was not passed and could not be determined from the environment.<p></p> An email notification with exception reason and trace log has been sent to [exceptions@aviatrix.com](mailto:exceptions@aviatrix.com) for troubleshooting. Please feel free to contact Aviatrix support. We apologize for this inconvenience and we thank you for your support.
│
│   with module.gcp_transit.module.mc_firenet_ha_gcp.aviatrix_firewall_instance.firewall_instance_2[0],
│   on .terraform/modules/gcp_transit.mc_firenet_ha_gcp/main.tf line 71, in resource "aviatrix_firewall_instance" "firewall_instance_2":
│   71: resource "aviatrix_firewall_instance" "firewall_instance_2" {
│

 

When I Created Firewall instance from UI with same name (firewall_instance_1), I observed below error.

Error: Invalid Instance name "firewall_instance_1". The maximum length for a Google Instance name is 50, name must start, with a lowercase letter followed by up to 49 lowercase letters, numbers, or hyphens, and cannot end with a hyphen.

**Comment by Dennizz** [comment]
Resolved. Not a module issue.
